# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  image  = "bento/ubuntu-20.04"
  workers  = 2
  
  config.vm.define "manager" do |manager|
    manager.vm.box = image
    manager.vm.hostname = "manager"
    manager.vm.network "private_network", ip: "192.168.33.10"
    manager.vm.synced_folder "../Ansible/", "/home/vagrant/Ansible/", create: true
    manager.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.memory = 2048
      vb.cpus = 1
    end
    manager.vm.provision "shell" do |s|
      s.inline = "sudo apt-get install ansible sshpass -y"
    end
  end

  (1..workers).each do |i|
    config.vm.define "worker#{i}" do |worker|
      worker.vm.box = image
      worker.vm.hostname = "worker#{i}"
      worker.vm.network "private_network", ip: "192.168.33.1#{i}"
      worker.vm.provider "virtualbox" do |vb|
        vb.gui = false
        vb.memory = 1024
        vb.cpus = 1
      end
    end
  end

end
