# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  image  = "bento/ubuntu-20.04"
  
  config.vm.define "manager" do |manager|
    manager.vm.box = image
    manager.vm.hostname = "manager"
    manager.vm.network "public_network"
    manager.vm.network "private_network", ip: "192.168.33.10"
    manager.vm.synced_folder "../Ansible/", "/home/vagrant/Ansible/", create: true
    manager.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.memory = 2048
      vb.cpus = 2
    end
    manager.vm.provision "shell" do |s|
      s.inline = "sudo apt-get install ansible sshpass -y"
    end
  end

end
