---
- name: Clean Docker
  apt:
    pkg:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
    state: absent
    force_apt_get: yes

- name: Setup HTTPS Repository
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    state: present
    update_cache: yes
    force_apt_get: yes

- name: Add Docker GPG key
  apt_key:
    keyserver: https://download.docker.com/linux/ubuntu/gpg
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    state: present

- name: Register Distribution
  shell: lsb_release -cs 
  register: lsb_release

- name: Add Docker Repository
  apt_repository:
    repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ lsb_release.stdout }} stable'
    state: present 

- name: Install Docker
  apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
    update_cache: yes
    force_apt_get: yes
  notify:
    - Start Docker
    - Enable Docker

- name: Add remote user to Docker group
  user:
    name: '{{ user }}'
    groups: 
      - docker
    append: yes

- name: Test Docker
  shell: docker run hello-world && docker rmi -f hello-world && docker container prune -f
