---
- name: Register System
  shell: uname -s
  register: sys
- name: Register Architecture
  shell: uname -m
  register: arch

- name: Install Docker-Compose
  get_url: 
    url: 'https://github.com/docker/compose/releases/download/1.28.2/docker-compose-{{ sys.stdout }}-{{ arch.stdout }}'
    dest: /usr/local/bin/docker-compose
    group: docker
    mode: 'u+x,g+x'

- name: Symlinking Docker-Compose
  file:
    src: /usr/local/bin/docker-compose
    dest: /usr/bin/docker-compose
    group: docker
    state: link
