---
- name: Initialize Swarm
  shell: "docker swarm init --advertise-addr {{ host }} || echo Cluster Exists"

- name: Run Visualize
  shell: docker run --restart=always --name visualizer -d -p 5000:8080 -v /var/run/docker.sock:/var/run/docker.sock dockersamples/visualizer || echo Port Used

- name: Setup NFS Directory
  become: yes
  file:
    path: /nfs
    recurse: yes
    state: directory
    mode: '0755'

- name: Run NFS Server
  shell: "docker run --restart=always -d --name nfs --privileged -v /nfs:/nfs -e SHARED_DIRECTORY=/nfs -p 2049:2048 itsthenetwork/nfs-server-alpine:latest || echo Port Used"

- name: Register Worker Token
  shell: docker swarm join-token -q worker
  register: token

- name: Save Worker Token
  add_host:
    name:   "TokenHolder"
    token:  "{{ token.stdout }}"
