---
- name: Clean System
  apt:
    autoremove: yes
    force_apt_get: yes

- name: Upgrade System
  apt:
    upgrade: 'yes'
    update_cache: yes
    force_apt_get: yes

- name: Install Python
  apt:
    pkg:
      - python3
      - python3-pip
    state: present
    update_cache: yes
    force_apt_get: yes

- name: Install Apt HTTPS Tools and NFS Client
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
      - nfs-common
    state: present
    update_cache: yes
    force_apt_get: yes
