---
- name: Clean System
  apt:
    autoremove: yes
    force_apt_get: yes

- name: Upgrade System
  apt:
    upgrade: 'yes'
    update_cache: yes
    force_apt_get: yes

- name: Setup Python
  apt:
    pkg:
      - python3
      - python3-pip
    state: present
    update_cache: yes
    force_apt_get: yes

