---
- name: Setup System
  hosts: all
  become: yes
  tasks:
    - include: tasks/system.yaml

- name: Setup Docker
  hosts: all
  become: yes
  tasks:
    - include: tasks/docker.yaml
  handlers:
    - include: handlers/docker.yaml

- name: Setup Docker-Compose
  hosts: manager
  become: yes
  tasks:
    - include: tasks/dockercompose.yaml

- name: Setup Jenkins
  hosts: manager
  become: yes
  tasks:
    - include: tasks/jenkins.yaml
  handlers:
    - include: handlers/jenkins.yaml
